### ISSUE TITLE
Reference and notes on https://political-generator.herokuapp.com/ ?

### ISSUE THREAD

**Issue by DonaldTsang** [DanielPBak/IdeologyGenerator#9]
They look very different, but at the same time, they try to do similar things. What are the differences?
Also http://enneadgames.com/generators/political-ideology-generator/ and https://perchance.org/ideologygenerator are not helping.

**Comment by DanielPBak** [comment]
I'm not sure what the question is.

**Comment by DonaldTsang** [comment]
To clarify, I do think that they behave similarly, but from a pure observation standpoint they use different methods to generate string combinations. Would it be good to oberve the difference at least?

**Comment by DanielPBak** [comment]
I don't understand what you're asking.

You can observe whatever differences you want. I have no idea how the other generators work.
